apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysite
  template:
    metadata:
      labels:
        app: mysite
    spec:
      containers:
      - name: mysite
        image: mysite:v2
        ports:
        - containerPort: 80
